### ISSUE TITLE
Overlay Link in Readme outdated.

### ISSUE THREAD

**Issue by ReikoTigon** [kOFReadie/BSDP-Overlay#3]
Hi, just wanted to mention that the Link in the README.md titled "Overlay" leads to a 404 page.

Could it be, that it's now routed over "http://u.readie.global-gaming.co/bsdp-overlay/"?

**Comment by JComins000** [comment]
the element visibility part also repeats itself
https://github.com/kOFReadie/BSDP-Overlay#element-visibility

**Comment by kOFReadie** [comment]
Thanks for letting me know ;) Ill fix it now, been working a lot on the overlay editor recently, hadn't been paying attention to these things.
