### ISSUE TITLE
would be useful if you said how to get it working

### ISSUE THREAD

**Issue by XxVGVxX** [kOFReadie/BSDP-Overlay#4]
you literally never mention how to install it, so maybe tell us

**Comment by XxVGVxX** [comment]
i just found it, please put it up on the page of the overlay itself as well, so others don't get confused

**Comment by kOFReadie** [comment]
> you literally never mention how to install it, so maybe tell us

It literally says how to install it in the first block, I'm updating the main mod for BS soon with multi support etc. Just going through some final tests.
