### ISSUE TITLE
Is hideModifiersHealth not an option anymore?

### ISSUE THREAD

**Issue by derpyjul45** [kOFReadie/BSDP-Overlay#6]
I couldn't use this old parameter to hide the health and modifiers for the 1.13.4 update (I tried checking the source js script on the overlay). Also I think some parameters changed such as hideHori and hideVerti (i think it used to be hideHoriz and hideVert).

**Comment by ZomB-assassin27** [comment]
I also couldn't use some of the settings which is annoying.

**Comment by kOFReadie** [comment]
Sorry, this update was taken from my rebuild on the dev branch. I have clearly forgotten to add some feaures into there. When I get round to it Ill add all of those missing features back and some more. Sorry about that.

**Comment by kOFReadie** [comment]
The features have been adde back with the '[Added missing features](https://github.com/kOFReadie/BSDP-Overlay/commit/33bc669872abc22e31cd7afa62676a73c8534497)' commit.  
The `flipVert` parameter has been renamed to `flipVerti` and you can now customise the overlay colours, read [here](https://github.com/kOFReadie/BSDP-Overlay/tree/307a47dfc4b7f70dab61a54bbe2c6b349b54d921#colours) for that
